server:
  port: 8002
spring:
  application:
    name: tensquare-recruit #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://148.70.63.176:33306/tensquare_recruit?characterEncoding=utf-8
    username: root
    password: 950613
  jpa:
    database: MySQL
    show-sql: true