server:
  port: 8001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://148.70.63.176:33306/tensquare_base?characterEncoding=utf-8
    username: root
    password: 950613
  jpa:
    show-sql: true
    database: mysql
    generate-ddl: false